/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * API version: 2.10.0
 * Contact: devex-public@okta.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FipsEnum string

// List of FipsEnum
const (
	REQUIRED_FipsEnum FipsEnum = "REQUIRED"
	OPTIONAL_FipsEnum FipsEnum = "OPTIONAL"
)
