/*
Okta Admin Management

Testing InlineHookAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okta

import (
	"context"
	"testing"

	openapiclient "github.com/okta/okta-sdk-golang/v6/okta"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_okta_InlineHookAPIService(t *testing.T) {

	configuration, err := openapiclient.NewConfiguration()
	require.Nil(t, err)
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InlineHookAPIService ActivateInlineHook", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var inlineHookId string

		resp, httpRes, err := apiClient.InlineHookAPI.ActivateInlineHook(context.Background(), inlineHookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InlineHookAPIService CreateInlineHook", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.InlineHookAPI.CreateInlineHook(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InlineHookAPIService DeactivateInlineHook", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var inlineHookId string

		resp, httpRes, err := apiClient.InlineHookAPI.DeactivateInlineHook(context.Background(), inlineHookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InlineHookAPIService DeleteInlineHook", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var inlineHookId string

		httpRes, err := apiClient.InlineHookAPI.DeleteInlineHook(context.Background(), inlineHookId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InlineHookAPIService ExecuteInlineHook", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var inlineHookId string

		resp, httpRes, err := apiClient.InlineHookAPI.ExecuteInlineHook(context.Background(), inlineHookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InlineHookAPIService GetInlineHook", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var inlineHookId string

		resp, httpRes, err := apiClient.InlineHookAPI.GetInlineHook(context.Background(), inlineHookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InlineHookAPIService ListInlineHooks", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.InlineHookAPI.ListInlineHooks(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InlineHookAPIService ReplaceInlineHook", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var inlineHookId string

		resp, httpRes, err := apiClient.InlineHookAPI.ReplaceInlineHook(context.Background(), inlineHookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InlineHookAPIService UpdateInlineHook", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var inlineHookId string

		resp, httpRes, err := apiClient.InlineHookAPI.UpdateInlineHook(context.Background(), inlineHookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
