name: Bug Report
description: Report a bug you encountered with the Okta Go SDK
labels: [ bug ]
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the bug?
      description: |
        Please be as detailed as possible. This will help us address the bug in a timely manner.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What is expected to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: What is the actual behavior?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps?
      description: |
        Please provide as much detail as possible to help us reproduce your bug.
        A reproduction repo is very helpful for us as well.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information?

  - type: textarea
    id: goVersion
    attributes:
      label: Golang Version
      description: |
        ```console
        $ go version
        # paste output here
        ```
    validations:
      required: true

  - type: textarea
    id: sdkVersion
    attributes:
      label: SDK Version
      description: |
        ```console
        $ make sdk-version
        # paste output here
        ```
    validations:
      required: true

  - type: textarea
    id: osVersion
    attributes:
      label: OS version
      description: |
        ```console
        # On Linux:
        $ cat /etc/os-release
        # paste output here

        # On Mac:
        $ uname -a
        # paste output here

        # On Windows:
        C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
        # paste output here
        ```
