contact_links:
  - name: Developer Forum
    url: https://devforum.okta.com/
    about: Get help with building your applicaiton on the Okta Platform.
  - name: Security
    url: https://www.okta.com/vulnerability-reporting-policy/
    about: At Okta we take the protection of our customers’ data very seriously.
blank_issues_enabled: false
