/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * API version: 2.8.1
 * Contact: devex-public@okta.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NetworkZoneAddress struct {
	Type_ *NetworkZoneAddressType `json:"type,omitempty"`
	Value string `json:"value,omitempty"`
}
