/*
 * Okta API
 *
 * Allows customers to easily access the Okta API
 *
 * API version: 2.8.1
 * Contact: devex-public@okta.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineHookType string

// List of InlineHookType
const (
	OAUTH2TOKENSTRANSFORM_InlineHookType InlineHookType = "com.okta.oauth2.tokens.transform"
	IMPORTTRANSFORM_InlineHookType InlineHookType = "com.okta.import.transform"
	SAMLTOKENSTRANSFORM_InlineHookType InlineHookType = "com.okta.saml.tokens.transform"
	USERPRE_REGISTRATION_InlineHookType InlineHookType = "com.okta.user.pre-registration"
	USERCREDENTIALPASSWORDIMPORT_InlineHookType InlineHookType = "com.okta.user.credential.password.import"
)
