/*
Okta Admin Management

Allows customers to easily access the Okta Management APIs

Copyright 2018 - Present Okta, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

API version: 5.1.0
Contact: devex-public@okta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package okta

import (
	"encoding/json"
)

// AuthenticatorMethodOtpAllOf struct for AuthenticatorMethodOtpAllOf
type AuthenticatorMethodOtpAllOf struct {
	AcceptableAdjacentIntervals *int32            `json:"acceptableAdjacentIntervals,omitempty"`
	Algorithm                   *OtpTotpAlgorithm `json:"algorithm,omitempty"`
	Encoding                    *OtpTotpEncoding  `json:"encoding,omitempty"`
	FactorProfileId             *string           `json:"factorProfileId,omitempty"`
	PassCodeLength              *int32            `json:"passCodeLength,omitempty"`
	Protocol                    *OtpProtocol      `json:"protocol,omitempty"`
	TimeIntervalInSeconds       *int32            `json:"timeIntervalInSeconds,omitempty"`
	AdditionalProperties        map[string]interface{}
}

type _AuthenticatorMethodOtpAllOf AuthenticatorMethodOtpAllOf

// NewAuthenticatorMethodOtpAllOf instantiates a new AuthenticatorMethodOtpAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticatorMethodOtpAllOf() *AuthenticatorMethodOtpAllOf {
	this := AuthenticatorMethodOtpAllOf{}
	return &this
}

// NewAuthenticatorMethodOtpAllOfWithDefaults instantiates a new AuthenticatorMethodOtpAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticatorMethodOtpAllOfWithDefaults() *AuthenticatorMethodOtpAllOf {
	this := AuthenticatorMethodOtpAllOf{}
	return &this
}

// GetAcceptableAdjacentIntervals returns the AcceptableAdjacentIntervals field value if set, zero value otherwise.
func (o *AuthenticatorMethodOtpAllOf) GetAcceptableAdjacentIntervals() int32 {
	if o == nil || o.AcceptableAdjacentIntervals == nil {
		var ret int32
		return ret
	}
	return *o.AcceptableAdjacentIntervals
}

// GetAcceptableAdjacentIntervalsOk returns a tuple with the AcceptableAdjacentIntervals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorMethodOtpAllOf) GetAcceptableAdjacentIntervalsOk() (*int32, bool) {
	if o == nil || o.AcceptableAdjacentIntervals == nil {
		return nil, false
	}
	return o.AcceptableAdjacentIntervals, true
}

// HasAcceptableAdjacentIntervals returns a boolean if a field has been set.
func (o *AuthenticatorMethodOtpAllOf) HasAcceptableAdjacentIntervals() bool {
	if o != nil && o.AcceptableAdjacentIntervals != nil {
		return true
	}

	return false
}

// SetAcceptableAdjacentIntervals gets a reference to the given int32 and assigns it to the AcceptableAdjacentIntervals field.
func (o *AuthenticatorMethodOtpAllOf) SetAcceptableAdjacentIntervals(v int32) {
	o.AcceptableAdjacentIntervals = &v
}

// GetAlgorithm returns the Algorithm field value if set, zero value otherwise.
func (o *AuthenticatorMethodOtpAllOf) GetAlgorithm() OtpTotpAlgorithm {
	if o == nil || o.Algorithm == nil {
		var ret OtpTotpAlgorithm
		return ret
	}
	return *o.Algorithm
}

// GetAlgorithmOk returns a tuple with the Algorithm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorMethodOtpAllOf) GetAlgorithmOk() (*OtpTotpAlgorithm, bool) {
	if o == nil || o.Algorithm == nil {
		return nil, false
	}
	return o.Algorithm, true
}

// HasAlgorithm returns a boolean if a field has been set.
func (o *AuthenticatorMethodOtpAllOf) HasAlgorithm() bool {
	if o != nil && o.Algorithm != nil {
		return true
	}

	return false
}

// SetAlgorithm gets a reference to the given OtpTotpAlgorithm and assigns it to the Algorithm field.
func (o *AuthenticatorMethodOtpAllOf) SetAlgorithm(v OtpTotpAlgorithm) {
	o.Algorithm = &v
}

// GetEncoding returns the Encoding field value if set, zero value otherwise.
func (o *AuthenticatorMethodOtpAllOf) GetEncoding() OtpTotpEncoding {
	if o == nil || o.Encoding == nil {
		var ret OtpTotpEncoding
		return ret
	}
	return *o.Encoding
}

// GetEncodingOk returns a tuple with the Encoding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorMethodOtpAllOf) GetEncodingOk() (*OtpTotpEncoding, bool) {
	if o == nil || o.Encoding == nil {
		return nil, false
	}
	return o.Encoding, true
}

// HasEncoding returns a boolean if a field has been set.
func (o *AuthenticatorMethodOtpAllOf) HasEncoding() bool {
	if o != nil && o.Encoding != nil {
		return true
	}

	return false
}

// SetEncoding gets a reference to the given OtpTotpEncoding and assigns it to the Encoding field.
func (o *AuthenticatorMethodOtpAllOf) SetEncoding(v OtpTotpEncoding) {
	o.Encoding = &v
}

// GetFactorProfileId returns the FactorProfileId field value if set, zero value otherwise.
func (o *AuthenticatorMethodOtpAllOf) GetFactorProfileId() string {
	if o == nil || o.FactorProfileId == nil {
		var ret string
		return ret
	}
	return *o.FactorProfileId
}

// GetFactorProfileIdOk returns a tuple with the FactorProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorMethodOtpAllOf) GetFactorProfileIdOk() (*string, bool) {
	if o == nil || o.FactorProfileId == nil {
		return nil, false
	}
	return o.FactorProfileId, true
}

// HasFactorProfileId returns a boolean if a field has been set.
func (o *AuthenticatorMethodOtpAllOf) HasFactorProfileId() bool {
	if o != nil && o.FactorProfileId != nil {
		return true
	}

	return false
}

// SetFactorProfileId gets a reference to the given string and assigns it to the FactorProfileId field.
func (o *AuthenticatorMethodOtpAllOf) SetFactorProfileId(v string) {
	o.FactorProfileId = &v
}

// GetPassCodeLength returns the PassCodeLength field value if set, zero value otherwise.
func (o *AuthenticatorMethodOtpAllOf) GetPassCodeLength() int32 {
	if o == nil || o.PassCodeLength == nil {
		var ret int32
		return ret
	}
	return *o.PassCodeLength
}

// GetPassCodeLengthOk returns a tuple with the PassCodeLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorMethodOtpAllOf) GetPassCodeLengthOk() (*int32, bool) {
	if o == nil || o.PassCodeLength == nil {
		return nil, false
	}
	return o.PassCodeLength, true
}

// HasPassCodeLength returns a boolean if a field has been set.
func (o *AuthenticatorMethodOtpAllOf) HasPassCodeLength() bool {
	if o != nil && o.PassCodeLength != nil {
		return true
	}

	return false
}

// SetPassCodeLength gets a reference to the given int32 and assigns it to the PassCodeLength field.
func (o *AuthenticatorMethodOtpAllOf) SetPassCodeLength(v int32) {
	o.PassCodeLength = &v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *AuthenticatorMethodOtpAllOf) GetProtocol() OtpProtocol {
	if o == nil || o.Protocol == nil {
		var ret OtpProtocol
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorMethodOtpAllOf) GetProtocolOk() (*OtpProtocol, bool) {
	if o == nil || o.Protocol == nil {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *AuthenticatorMethodOtpAllOf) HasProtocol() bool {
	if o != nil && o.Protocol != nil {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given OtpProtocol and assigns it to the Protocol field.
func (o *AuthenticatorMethodOtpAllOf) SetProtocol(v OtpProtocol) {
	o.Protocol = &v
}

// GetTimeIntervalInSeconds returns the TimeIntervalInSeconds field value if set, zero value otherwise.
func (o *AuthenticatorMethodOtpAllOf) GetTimeIntervalInSeconds() int32 {
	if o == nil || o.TimeIntervalInSeconds == nil {
		var ret int32
		return ret
	}
	return *o.TimeIntervalInSeconds
}

// GetTimeIntervalInSecondsOk returns a tuple with the TimeIntervalInSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorMethodOtpAllOf) GetTimeIntervalInSecondsOk() (*int32, bool) {
	if o == nil || o.TimeIntervalInSeconds == nil {
		return nil, false
	}
	return o.TimeIntervalInSeconds, true
}

// HasTimeIntervalInSeconds returns a boolean if a field has been set.
func (o *AuthenticatorMethodOtpAllOf) HasTimeIntervalInSeconds() bool {
	if o != nil && o.TimeIntervalInSeconds != nil {
		return true
	}

	return false
}

// SetTimeIntervalInSeconds gets a reference to the given int32 and assigns it to the TimeIntervalInSeconds field.
func (o *AuthenticatorMethodOtpAllOf) SetTimeIntervalInSeconds(v int32) {
	o.TimeIntervalInSeconds = &v
}

func (o AuthenticatorMethodOtpAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AcceptableAdjacentIntervals != nil {
		toSerialize["acceptableAdjacentIntervals"] = o.AcceptableAdjacentIntervals
	}
	if o.Algorithm != nil {
		toSerialize["algorithm"] = o.Algorithm
	}
	if o.Encoding != nil {
		toSerialize["encoding"] = o.Encoding
	}
	if o.FactorProfileId != nil {
		toSerialize["factorProfileId"] = o.FactorProfileId
	}
	if o.PassCodeLength != nil {
		toSerialize["passCodeLength"] = o.PassCodeLength
	}
	if o.Protocol != nil {
		toSerialize["protocol"] = o.Protocol
	}
	if o.TimeIntervalInSeconds != nil {
		toSerialize["timeIntervalInSeconds"] = o.TimeIntervalInSeconds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AuthenticatorMethodOtpAllOf) UnmarshalJSON(bytes []byte) (err error) {
	varAuthenticatorMethodOtpAllOf := _AuthenticatorMethodOtpAllOf{}

	err = json.Unmarshal(bytes, &varAuthenticatorMethodOtpAllOf)
	if err == nil {
		*o = AuthenticatorMethodOtpAllOf(varAuthenticatorMethodOtpAllOf)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &additionalProperties)
	if err == nil {
		delete(additionalProperties, "acceptableAdjacentIntervals")
		delete(additionalProperties, "algorithm")
		delete(additionalProperties, "encoding")
		delete(additionalProperties, "factorProfileId")
		delete(additionalProperties, "passCodeLength")
		delete(additionalProperties, "protocol")
		delete(additionalProperties, "timeIntervalInSeconds")
		o.AdditionalProperties = additionalProperties
	} else {
		return err
	}

	return err
}

type NullableAuthenticatorMethodOtpAllOf struct {
	value *AuthenticatorMethodOtpAllOf
	isSet bool
}

func (v NullableAuthenticatorMethodOtpAllOf) Get() *AuthenticatorMethodOtpAllOf {
	return v.value
}

func (v *NullableAuthenticatorMethodOtpAllOf) Set(val *AuthenticatorMethodOtpAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticatorMethodOtpAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticatorMethodOtpAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticatorMethodOtpAllOf(val *AuthenticatorMethodOtpAllOf) *NullableAuthenticatorMethodOtpAllOf {
	return &NullableAuthenticatorMethodOtpAllOf{value: val, isSet: true}
}

func (v NullableAuthenticatorMethodOtpAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticatorMethodOtpAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
