/*
Okta Admin Management

Allows customers to easily access the Okta Management APIs

Copyright 2018 - Present Okta, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

API version: 4.0.0
Contact: devex-public@okta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package okta

import (
	"encoding/json"
)

// AuthorizationServerPolicyRuleConditionsAllOf struct for AuthorizationServerPolicyRuleConditionsAllOf
type AuthorizationServerPolicyRuleConditionsAllOf struct {
	Clients              *ClientPolicyCondition                    `json:"clients,omitempty"`
	GrantTypes           *GrantTypePolicyRuleCondition             `json:"grantTypes,omitempty"`
	People               *PolicyPeopleCondition                    `json:"people,omitempty"`
	Scopes               *OAuth2ScopesMediationPolicyRuleCondition `json:"scopes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AuthorizationServerPolicyRuleConditionsAllOf AuthorizationServerPolicyRuleConditionsAllOf

// NewAuthorizationServerPolicyRuleConditionsAllOf instantiates a new AuthorizationServerPolicyRuleConditionsAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizationServerPolicyRuleConditionsAllOf() *AuthorizationServerPolicyRuleConditionsAllOf {
	this := AuthorizationServerPolicyRuleConditionsAllOf{}
	return &this
}

// NewAuthorizationServerPolicyRuleConditionsAllOfWithDefaults instantiates a new AuthorizationServerPolicyRuleConditionsAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizationServerPolicyRuleConditionsAllOfWithDefaults() *AuthorizationServerPolicyRuleConditionsAllOf {
	this := AuthorizationServerPolicyRuleConditionsAllOf{}
	return &this
}

// GetClients returns the Clients field value if set, zero value otherwise.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) GetClients() ClientPolicyCondition {
	if o == nil || o.Clients == nil {
		var ret ClientPolicyCondition
		return ret
	}
	return *o.Clients
}

// GetClientsOk returns a tuple with the Clients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) GetClientsOk() (*ClientPolicyCondition, bool) {
	if o == nil || o.Clients == nil {
		return nil, false
	}
	return o.Clients, true
}

// HasClients returns a boolean if a field has been set.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) HasClients() bool {
	if o != nil && o.Clients != nil {
		return true
	}

	return false
}

// SetClients gets a reference to the given ClientPolicyCondition and assigns it to the Clients field.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) SetClients(v ClientPolicyCondition) {
	o.Clients = &v
}

// GetGrantTypes returns the GrantTypes field value if set, zero value otherwise.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) GetGrantTypes() GrantTypePolicyRuleCondition {
	if o == nil || o.GrantTypes == nil {
		var ret GrantTypePolicyRuleCondition
		return ret
	}
	return *o.GrantTypes
}

// GetGrantTypesOk returns a tuple with the GrantTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) GetGrantTypesOk() (*GrantTypePolicyRuleCondition, bool) {
	if o == nil || o.GrantTypes == nil {
		return nil, false
	}
	return o.GrantTypes, true
}

// HasGrantTypes returns a boolean if a field has been set.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) HasGrantTypes() bool {
	if o != nil && o.GrantTypes != nil {
		return true
	}

	return false
}

// SetGrantTypes gets a reference to the given GrantTypePolicyRuleCondition and assigns it to the GrantTypes field.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) SetGrantTypes(v GrantTypePolicyRuleCondition) {
	o.GrantTypes = &v
}

// GetPeople returns the People field value if set, zero value otherwise.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) GetPeople() PolicyPeopleCondition {
	if o == nil || o.People == nil {
		var ret PolicyPeopleCondition
		return ret
	}
	return *o.People
}

// GetPeopleOk returns a tuple with the People field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) GetPeopleOk() (*PolicyPeopleCondition, bool) {
	if o == nil || o.People == nil {
		return nil, false
	}
	return o.People, true
}

// HasPeople returns a boolean if a field has been set.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) HasPeople() bool {
	if o != nil && o.People != nil {
		return true
	}

	return false
}

// SetPeople gets a reference to the given PolicyPeopleCondition and assigns it to the People field.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) SetPeople(v PolicyPeopleCondition) {
	o.People = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) GetScopes() OAuth2ScopesMediationPolicyRuleCondition {
	if o == nil || o.Scopes == nil {
		var ret OAuth2ScopesMediationPolicyRuleCondition
		return ret
	}
	return *o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) GetScopesOk() (*OAuth2ScopesMediationPolicyRuleCondition, bool) {
	if o == nil || o.Scopes == nil {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) HasScopes() bool {
	if o != nil && o.Scopes != nil {
		return true
	}

	return false
}

// SetScopes gets a reference to the given OAuth2ScopesMediationPolicyRuleCondition and assigns it to the Scopes field.
func (o *AuthorizationServerPolicyRuleConditionsAllOf) SetScopes(v OAuth2ScopesMediationPolicyRuleCondition) {
	o.Scopes = &v
}

func (o AuthorizationServerPolicyRuleConditionsAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Clients != nil {
		toSerialize["clients"] = o.Clients
	}
	if o.GrantTypes != nil {
		toSerialize["grantTypes"] = o.GrantTypes
	}
	if o.People != nil {
		toSerialize["people"] = o.People
	}
	if o.Scopes != nil {
		toSerialize["scopes"] = o.Scopes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AuthorizationServerPolicyRuleConditionsAllOf) UnmarshalJSON(bytes []byte) (err error) {
	varAuthorizationServerPolicyRuleConditionsAllOf := _AuthorizationServerPolicyRuleConditionsAllOf{}

	err = json.Unmarshal(bytes, &varAuthorizationServerPolicyRuleConditionsAllOf)
	if err == nil {
		*o = AuthorizationServerPolicyRuleConditionsAllOf(varAuthorizationServerPolicyRuleConditionsAllOf)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &additionalProperties)
	if err == nil {
		delete(additionalProperties, "clients")
		delete(additionalProperties, "grantTypes")
		delete(additionalProperties, "people")
		delete(additionalProperties, "scopes")
		o.AdditionalProperties = additionalProperties
	} else {
		return err
	}

	return err
}

type NullableAuthorizationServerPolicyRuleConditionsAllOf struct {
	value *AuthorizationServerPolicyRuleConditionsAllOf
	isSet bool
}

func (v NullableAuthorizationServerPolicyRuleConditionsAllOf) Get() *AuthorizationServerPolicyRuleConditionsAllOf {
	return v.value
}

func (v *NullableAuthorizationServerPolicyRuleConditionsAllOf) Set(val *AuthorizationServerPolicyRuleConditionsAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizationServerPolicyRuleConditionsAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizationServerPolicyRuleConditionsAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizationServerPolicyRuleConditionsAllOf(val *AuthorizationServerPolicyRuleConditionsAllOf) *NullableAuthorizationServerPolicyRuleConditionsAllOf {
	return &NullableAuthorizationServerPolicyRuleConditionsAllOf{value: val, isSet: true}
}

func (v NullableAuthorizationServerPolicyRuleConditionsAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizationServerPolicyRuleConditionsAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
