/*
Okta Admin Management

Allows customers to easily access the Okta Management APIs

Copyright 2018 - Present Okta, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

API version: 5.1.0
Contact: devex-public@okta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package okta

import (
	"encoding/json"
)

// ResourceSetBindingMembersLinksAllOf struct for ResourceSetBindingMembersLinksAllOf
type ResourceSetBindingMembersLinksAllOf struct {
	Binding              *HrefObject `json:"binding,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ResourceSetBindingMembersLinksAllOf ResourceSetBindingMembersLinksAllOf

// NewResourceSetBindingMembersLinksAllOf instantiates a new ResourceSetBindingMembersLinksAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceSetBindingMembersLinksAllOf() *ResourceSetBindingMembersLinksAllOf {
	this := ResourceSetBindingMembersLinksAllOf{}
	return &this
}

// NewResourceSetBindingMembersLinksAllOfWithDefaults instantiates a new ResourceSetBindingMembersLinksAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceSetBindingMembersLinksAllOfWithDefaults() *ResourceSetBindingMembersLinksAllOf {
	this := ResourceSetBindingMembersLinksAllOf{}
	return &this
}

// GetBinding returns the Binding field value if set, zero value otherwise.
func (o *ResourceSetBindingMembersLinksAllOf) GetBinding() HrefObject {
	if o == nil || o.Binding == nil {
		var ret HrefObject
		return ret
	}
	return *o.Binding
}

// GetBindingOk returns a tuple with the Binding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceSetBindingMembersLinksAllOf) GetBindingOk() (*HrefObject, bool) {
	if o == nil || o.Binding == nil {
		return nil, false
	}
	return o.Binding, true
}

// HasBinding returns a boolean if a field has been set.
func (o *ResourceSetBindingMembersLinksAllOf) HasBinding() bool {
	if o != nil && o.Binding != nil {
		return true
	}

	return false
}

// SetBinding gets a reference to the given HrefObject and assigns it to the Binding field.
func (o *ResourceSetBindingMembersLinksAllOf) SetBinding(v HrefObject) {
	o.Binding = &v
}

func (o ResourceSetBindingMembersLinksAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Binding != nil {
		toSerialize["binding"] = o.Binding
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ResourceSetBindingMembersLinksAllOf) UnmarshalJSON(bytes []byte) (err error) {
	varResourceSetBindingMembersLinksAllOf := _ResourceSetBindingMembersLinksAllOf{}

	err = json.Unmarshal(bytes, &varResourceSetBindingMembersLinksAllOf)
	if err == nil {
		*o = ResourceSetBindingMembersLinksAllOf(varResourceSetBindingMembersLinksAllOf)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &additionalProperties)
	if err == nil {
		delete(additionalProperties, "binding")
		o.AdditionalProperties = additionalProperties
	} else {
		return err
	}

	return err
}

type NullableResourceSetBindingMembersLinksAllOf struct {
	value *ResourceSetBindingMembersLinksAllOf
	isSet bool
}

func (v NullableResourceSetBindingMembersLinksAllOf) Get() *ResourceSetBindingMembersLinksAllOf {
	return v.value
}

func (v *NullableResourceSetBindingMembersLinksAllOf) Set(val *ResourceSetBindingMembersLinksAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceSetBindingMembersLinksAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceSetBindingMembersLinksAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceSetBindingMembersLinksAllOf(val *ResourceSetBindingMembersLinksAllOf) *NullableResourceSetBindingMembersLinksAllOf {
	return &NullableResourceSetBindingMembersLinksAllOf{value: val, isSet: true}
}

func (v NullableResourceSetBindingMembersLinksAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceSetBindingMembersLinksAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
