/*
Okta Admin Management

Allows customers to easily access the Okta Management APIs

Copyright 2018 - Present Okta, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

API version: 5.1.0
Contact: devex-public@okta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package okta

import (
	"encoding/json"
)

// AuthenticatorMethodSignedNonceAllOf struct for AuthenticatorMethodSignedNonceAllOf
type AuthenticatorMethodSignedNonceAllOf struct {
	Settings             *AuthenticatorMethodSignedNonceAllOfSettings `json:"settings,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AuthenticatorMethodSignedNonceAllOf AuthenticatorMethodSignedNonceAllOf

// NewAuthenticatorMethodSignedNonceAllOf instantiates a new AuthenticatorMethodSignedNonceAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticatorMethodSignedNonceAllOf() *AuthenticatorMethodSignedNonceAllOf {
	this := AuthenticatorMethodSignedNonceAllOf{}
	return &this
}

// NewAuthenticatorMethodSignedNonceAllOfWithDefaults instantiates a new AuthenticatorMethodSignedNonceAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticatorMethodSignedNonceAllOfWithDefaults() *AuthenticatorMethodSignedNonceAllOf {
	this := AuthenticatorMethodSignedNonceAllOf{}
	return &this
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *AuthenticatorMethodSignedNonceAllOf) GetSettings() AuthenticatorMethodSignedNonceAllOfSettings {
	if o == nil || o.Settings == nil {
		var ret AuthenticatorMethodSignedNonceAllOfSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorMethodSignedNonceAllOf) GetSettingsOk() (*AuthenticatorMethodSignedNonceAllOfSettings, bool) {
	if o == nil || o.Settings == nil {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *AuthenticatorMethodSignedNonceAllOf) HasSettings() bool {
	if o != nil && o.Settings != nil {
		return true
	}

	return false
}

// SetSettings gets a reference to the given AuthenticatorMethodSignedNonceAllOfSettings and assigns it to the Settings field.
func (o *AuthenticatorMethodSignedNonceAllOf) SetSettings(v AuthenticatorMethodSignedNonceAllOfSettings) {
	o.Settings = &v
}

func (o AuthenticatorMethodSignedNonceAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Settings != nil {
		toSerialize["settings"] = o.Settings
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AuthenticatorMethodSignedNonceAllOf) UnmarshalJSON(bytes []byte) (err error) {
	varAuthenticatorMethodSignedNonceAllOf := _AuthenticatorMethodSignedNonceAllOf{}

	err = json.Unmarshal(bytes, &varAuthenticatorMethodSignedNonceAllOf)
	if err == nil {
		*o = AuthenticatorMethodSignedNonceAllOf(varAuthenticatorMethodSignedNonceAllOf)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &additionalProperties)
	if err == nil {
		delete(additionalProperties, "settings")
		o.AdditionalProperties = additionalProperties
	} else {
		return err
	}

	return err
}

type NullableAuthenticatorMethodSignedNonceAllOf struct {
	value *AuthenticatorMethodSignedNonceAllOf
	isSet bool
}

func (v NullableAuthenticatorMethodSignedNonceAllOf) Get() *AuthenticatorMethodSignedNonceAllOf {
	return v.value
}

func (v *NullableAuthenticatorMethodSignedNonceAllOf) Set(val *AuthenticatorMethodSignedNonceAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticatorMethodSignedNonceAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticatorMethodSignedNonceAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticatorMethodSignedNonceAllOf(val *AuthenticatorMethodSignedNonceAllOf) *NullableAuthenticatorMethodSignedNonceAllOf {
	return &NullableAuthenticatorMethodSignedNonceAllOf{value: val, isSet: true}
}

func (v NullableAuthenticatorMethodSignedNonceAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticatorMethodSignedNonceAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
