name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked stale because there has been no activity within the last 14 days. To keep this issue active, remove the `stale` label, or it will be closed in 5 days.'
        stale-pr-message: 'This PR has been marked stale because there has been no activity within the last 28 days. To keep this PR active, remove the `stale` label, or it will be closed in 10 days.'
        close-issue-message: 'This issue was closed due to inactivity in the last 19 days. If this is still an issue, please reach back out and re-open this issue and remove the `stale` label.'
        close-pr-message: 'This PR was closed due to inactivity in the last 39 days. If this PR is still necessary, please re-open and remove the `stale` label.'
        days-before-issue-stale: 14
        days-before-pr-stale: 28
        days-before-issue-close: 5
        days-before-pr-close: 10
        exempt-issue-labels: 'no-stalebot'
        exempt-pr-labels: 'no-stalebot'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'