name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked stale because there has been no activity within the last 14 days. To keep this issue active, remove the `stale` label.'
        stale-pr-message: 'This PR has been marked stale because there has been no activity within the last 28 days. To keep this PR active, remove the `stale` label.'
        days-before-issue-stale: 14
        days-before-pr-stale: 28
        days-before-close: -1
        exempt-issue-labels: 'no-stalebot'
        exempt-pr-labels: 'no-stalebot'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
